# coding: utf-8

"""
    Amun API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from amun.swagger_client.api_client import ApiClient


class InspectionApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_inspect_build_log(self, inspection_id, **kwargs):  # noqa: E501
        """Get log for a specific inspection build.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_inspect_build_log(inspection_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str inspection_id: Id of inspection build. (required)
        :return: InspectionBuildLogResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_inspect_build_log_with_http_info(inspection_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_inspect_build_log_with_http_info(inspection_id, **kwargs)  # noqa: E501
            return data

    def get_inspect_build_log_with_http_info(self, inspection_id, **kwargs):  # noqa: E501
        """Get log for a specific inspection build.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_inspect_build_log_with_http_info(inspection_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str inspection_id: Id of inspection build. (required)
        :return: InspectionBuildLogResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['inspection_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_inspect_build_log" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'inspection_id' is set
        if ('inspection_id' not in params or
                params['inspection_id'] is None):
            raise ValueError("Missing the required parameter `inspection_id` when calling `get_inspect_build_log`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'inspection_id' in params:
            path_params['inspection_id'] = params['inspection_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/inspect/{inspection_id}/build/log', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InspectionBuildLogResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_inspect_build_status(self, inspection_id, **kwargs):  # noqa: E501
        """Get status of a build run.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_inspect_build_status(inspection_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str inspection_id: Id of inspection run. (required)
        :return: InspectionBuildStatusResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_inspect_build_status_with_http_info(inspection_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_inspect_build_status_with_http_info(inspection_id, **kwargs)  # noqa: E501
            return data

    def get_inspect_build_status_with_http_info(self, inspection_id, **kwargs):  # noqa: E501
        """Get status of a build run.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_inspect_build_status_with_http_info(inspection_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str inspection_id: Id of inspection run. (required)
        :return: InspectionBuildStatusResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['inspection_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_inspect_build_status" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'inspection_id' is set
        if ('inspection_id' not in params or
                params['inspection_id'] is None):
            raise ValueError("Missing the required parameter `inspection_id` when calling `get_inspect_build_status`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'inspection_id' in params:
            path_params['inspection_id'] = params['inspection_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/inspect/{inspection_id}/build/status', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InspectionBuildStatusResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_inspect_job_log(self, inspection_id, **kwargs):  # noqa: E501
        """Get log for a specific inspection run.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_inspect_job_log(inspection_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str inspection_id: Id of inspection run. (required)
        :return: InspectionRunLogResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_inspect_job_log_with_http_info(inspection_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_inspect_job_log_with_http_info(inspection_id, **kwargs)  # noqa: E501
            return data

    def get_inspect_job_log_with_http_info(self, inspection_id, **kwargs):  # noqa: E501
        """Get log for a specific inspection run.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_inspect_job_log_with_http_info(inspection_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str inspection_id: Id of inspection run. (required)
        :return: InspectionRunLogResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['inspection_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_inspect_job_log" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'inspection_id' is set
        if ('inspection_id' not in params or
                params['inspection_id'] is None):
            raise ValueError("Missing the required parameter `inspection_id` when calling `get_inspect_job_log`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'inspection_id' in params:
            path_params['inspection_id'] = params['inspection_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/inspect/{inspection_id}/job/log', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InspectionRunLogResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_inspect_job_status(self, inspection_id, **kwargs):  # noqa: E501
        """Get status of the application run.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_inspect_job_status(inspection_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str inspection_id: Id of inspection run. (required)
        :return: InspectionJobStatusResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_inspect_job_status_with_http_info(inspection_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_inspect_job_status_with_http_info(inspection_id, **kwargs)  # noqa: E501
            return data

    def get_inspect_job_status_with_http_info(self, inspection_id, **kwargs):  # noqa: E501
        """Get status of the application run.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_inspect_job_status_with_http_info(inspection_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str inspection_id: Id of inspection run. (required)
        :return: InspectionJobStatusResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['inspection_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_inspect_job_status" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'inspection_id' is set
        if ('inspection_id' not in params or
                params['inspection_id'] is None):
            raise ValueError("Missing the required parameter `inspection_id` when calling `get_inspect_job_status`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'inspection_id' in params:
            path_params['inspection_id'] = params['inspection_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/inspect/{inspection_id}/job/status', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InspectionJobStatusResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def post_inspect(self, specification, **kwargs):  # noqa: E501
        """Inspect the given application stack.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_inspect(specification, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param InspectionSpecification specification: Base image to be used for runtime environment. (required)
        :return: InspectionResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.post_inspect_with_http_info(specification, **kwargs)  # noqa: E501
        else:
            (data) = self.post_inspect_with_http_info(specification, **kwargs)  # noqa: E501
            return data

    def post_inspect_with_http_info(self, specification, **kwargs):  # noqa: E501
        """Inspect the given application stack.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_inspect_with_http_info(specification, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param InspectionSpecification specification: Base image to be used for runtime environment. (required)
        :return: InspectionResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['specification']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method post_inspect" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'specification' is set
        if ('specification' not in params or
                params['specification'] is None):
            raise ValueError("Missing the required parameter `specification` when calling `post_inspect`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'specification' in params:
            body_params = params['specification']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/inspect', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InspectionResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
